/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AccountSetupRouteImport } from './routes/account-setup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatusIndexRouteImport } from './routes/status.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as ChatsIndexRouteImport } from './routes/chats.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as CommunityCreatePostRouteImport } from './routes/community.create-post'
import { Route as CommunityCommunityIdRouteImport } from './routes/community.$communityId'
import { Route as ChatsNewRouteImport } from './routes/chats.new'
import { Route as ChatsChatIdRouteImport } from './routes/chats.$chatId'
import { Route as CommunityCommunityIdIndexRouteImport } from './routes/community.$communityId.index'
import { Route as CommunityCommunityIdMembersRouteImport } from './routes/community.$communityId.members'
import { Route as CommunityCommunityIdAboutRouteImport } from './routes/community.$communityId.about'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSetupRoute = AccountSetupRouteImport.update({
  id: '/account-setup',
  path: '/account-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusIndexRoute = StatusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatusRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatsRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityCreatePostRoute = CommunityCreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityCommunityIdRoute = CommunityCommunityIdRouteImport.update({
  id: '/$communityId',
  path: '/$communityId',
  getParentRoute: () => CommunityRoute,
} as any)
const ChatsNewRoute = ChatsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ChatsRoute,
} as any)
const ChatsChatIdRoute = ChatsChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => ChatsRoute,
} as any)
const CommunityCommunityIdIndexRoute =
  CommunityCommunityIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CommunityCommunityIdRoute,
  } as any)
const CommunityCommunityIdMembersRoute =
  CommunityCommunityIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => CommunityCommunityIdRoute,
  } as any)
const CommunityCommunityIdAboutRoute =
  CommunityCommunityIdAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => CommunityCommunityIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-setup': typeof AccountSetupRoute
  '/chats': typeof ChatsRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/create-account': typeof CreateAccountRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRouteWithChildren
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/chats/new': typeof ChatsNewRoute
  '/community/$communityId': typeof CommunityCommunityIdRouteWithChildren
  '/community/create-post': typeof CommunityCreatePostRoute
  '/u/$username': typeof UUsernameRoute
  '/chats/': typeof ChatsIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/status/': typeof StatusIndexRoute
  '/community/$communityId/about': typeof CommunityCommunityIdAboutRoute
  '/community/$communityId/members': typeof CommunityCommunityIdMembersRoute
  '/community/$communityId/': typeof CommunityCommunityIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-setup': typeof AccountSetupRoute
  '/contacts': typeof ContactsRoute
  '/create-account': typeof CreateAccountRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/settings': typeof SettingsRoute
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/chats/new': typeof ChatsNewRoute
  '/community/create-post': typeof CommunityCreatePostRoute
  '/u/$username': typeof UUsernameRoute
  '/chats': typeof ChatsIndexRoute
  '/community': typeof CommunityIndexRoute
  '/status': typeof StatusIndexRoute
  '/community/$communityId/about': typeof CommunityCommunityIdAboutRoute
  '/community/$communityId/members': typeof CommunityCommunityIdMembersRoute
  '/community/$communityId': typeof CommunityCommunityIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-setup': typeof AccountSetupRoute
  '/chats': typeof ChatsRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/create-account': typeof CreateAccountRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRouteWithChildren
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/chats/new': typeof ChatsNewRoute
  '/community/$communityId': typeof CommunityCommunityIdRouteWithChildren
  '/community/create-post': typeof CommunityCreatePostRoute
  '/u/$username': typeof UUsernameRoute
  '/chats/': typeof ChatsIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/status/': typeof StatusIndexRoute
  '/community/$communityId/about': typeof CommunityCommunityIdAboutRoute
  '/community/$communityId/members': typeof CommunityCommunityIdMembersRoute
  '/community/$communityId/': typeof CommunityCommunityIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-setup'
    | '/chats'
    | '/community'
    | '/contacts'
    | '/create-account'
    | '/home'
    | '/profile'
    | '/profile-setup'
    | '/settings'
    | '/status'
    | '/chats/$chatId'
    | '/chats/new'
    | '/community/$communityId'
    | '/community/create-post'
    | '/u/$username'
    | '/chats/'
    | '/community/'
    | '/status/'
    | '/community/$communityId/about'
    | '/community/$communityId/members'
    | '/community/$communityId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-setup'
    | '/contacts'
    | '/create-account'
    | '/home'
    | '/profile'
    | '/profile-setup'
    | '/settings'
    | '/chats/$chatId'
    | '/chats/new'
    | '/community/create-post'
    | '/u/$username'
    | '/chats'
    | '/community'
    | '/status'
    | '/community/$communityId/about'
    | '/community/$communityId/members'
    | '/community/$communityId'
  id:
    | '__root__'
    | '/'
    | '/account-setup'
    | '/chats'
    | '/community'
    | '/contacts'
    | '/create-account'
    | '/home'
    | '/profile'
    | '/profile-setup'
    | '/settings'
    | '/status'
    | '/chats/$chatId'
    | '/chats/new'
    | '/community/$communityId'
    | '/community/create-post'
    | '/u/$username'
    | '/chats/'
    | '/community/'
    | '/status/'
    | '/community/$communityId/about'
    | '/community/$communityId/members'
    | '/community/$communityId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSetupRoute: typeof AccountSetupRoute
  ChatsRoute: typeof ChatsRouteWithChildren
  CommunityRoute: typeof CommunityRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  CreateAccountRoute: typeof CreateAccountRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRouteWithChildren
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-setup': {
      id: '/account-setup'
      path: '/account-setup'
      fullPath: '/account-setup'
      preLoaderRoute: typeof AccountSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/': {
      id: '/status/'
      path: '/'
      fullPath: '/status/'
      preLoaderRoute: typeof StatusIndexRouteImport
      parentRoute: typeof StatusRoute
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/chats/': {
      id: '/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/create-post': {
      id: '/community/create-post'
      path: '/create-post'
      fullPath: '/community/create-post'
      preLoaderRoute: typeof CommunityCreatePostRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/$communityId': {
      id: '/community/$communityId'
      path: '/$communityId'
      fullPath: '/community/$communityId'
      preLoaderRoute: typeof CommunityCommunityIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/chats/new': {
      id: '/chats/new'
      path: '/new'
      fullPath: '/chats/new'
      preLoaderRoute: typeof ChatsNewRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/chats/$chatId': {
      id: '/chats/$chatId'
      path: '/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof ChatsChatIdRouteImport
      parentRoute: typeof ChatsRoute
    }
    '/community/$communityId/': {
      id: '/community/$communityId/'
      path: '/'
      fullPath: '/community/$communityId/'
      preLoaderRoute: typeof CommunityCommunityIdIndexRouteImport
      parentRoute: typeof CommunityCommunityIdRoute
    }
    '/community/$communityId/members': {
      id: '/community/$communityId/members'
      path: '/members'
      fullPath: '/community/$communityId/members'
      preLoaderRoute: typeof CommunityCommunityIdMembersRouteImport
      parentRoute: typeof CommunityCommunityIdRoute
    }
    '/community/$communityId/about': {
      id: '/community/$communityId/about'
      path: '/about'
      fullPath: '/community/$communityId/about'
      preLoaderRoute: typeof CommunityCommunityIdAboutRouteImport
      parentRoute: typeof CommunityCommunityIdRoute
    }
  }
}

interface ChatsRouteChildren {
  ChatsChatIdRoute: typeof ChatsChatIdRoute
  ChatsNewRoute: typeof ChatsNewRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsChatIdRoute: ChatsChatIdRoute,
  ChatsNewRoute: ChatsNewRoute,
  ChatsIndexRoute: ChatsIndexRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

interface CommunityCommunityIdRouteChildren {
  CommunityCommunityIdAboutRoute: typeof CommunityCommunityIdAboutRoute
  CommunityCommunityIdMembersRoute: typeof CommunityCommunityIdMembersRoute
  CommunityCommunityIdIndexRoute: typeof CommunityCommunityIdIndexRoute
}

const CommunityCommunityIdRouteChildren: CommunityCommunityIdRouteChildren = {
  CommunityCommunityIdAboutRoute: CommunityCommunityIdAboutRoute,
  CommunityCommunityIdMembersRoute: CommunityCommunityIdMembersRoute,
  CommunityCommunityIdIndexRoute: CommunityCommunityIdIndexRoute,
}

const CommunityCommunityIdRouteWithChildren =
  CommunityCommunityIdRoute._addFileChildren(CommunityCommunityIdRouteChildren)

interface CommunityRouteChildren {
  CommunityCommunityIdRoute: typeof CommunityCommunityIdRouteWithChildren
  CommunityCreatePostRoute: typeof CommunityCreatePostRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityCommunityIdRoute: CommunityCommunityIdRouteWithChildren,
  CommunityCreatePostRoute: CommunityCreatePostRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface StatusRouteChildren {
  StatusIndexRoute: typeof StatusIndexRoute
}

const StatusRouteChildren: StatusRouteChildren = {
  StatusIndexRoute: StatusIndexRoute,
}

const StatusRouteWithChildren =
  StatusRoute._addFileChildren(StatusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSetupRoute: AccountSetupRoute,
  ChatsRoute: ChatsRouteWithChildren,
  CommunityRoute: CommunityRouteWithChildren,
  ContactsRoute: ContactsRoute,
  CreateAccountRoute: CreateAccountRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRouteWithChildren,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
